# Generated by Django 3.2.7 on 2021-09-10 19:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('instap', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='profile_img',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='profile_pic/'),
            preserve_default=False,
        ),
    ]
